### ISSUE TITLE
Replacement for "Who's on First" data repository (assuming MapZen's is going away)

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#11]
With MapZen going away, we need a Who's on First replacement.

**Comment by missinglink** [comment]
This issue should now be resolved in the `master` branch of `pelias/whosonfirst` and tagged with the `latest` tag on dockerhub.

No configuration changes are required and the command remains the same `npm run download`

**Comment by missinglink** [comment]
The corresponding PR is https://github.com/pelias/whosonfirst/pull/324

You may now remove the `api_key` param from your `pelias.json` as it's no longer relevant, a PR has already been merged to update the OpenTransitTools docker repo https://github.com/OpenTransitTools/pelias.dockerfiles/pull/5

**Comment by missinglink** [comment]
I'm happy to mark this issue as closed unless there are any additional comments/suggestions/bugfixes?

**Comment by fpurcell** [comment]
thanks peter ... closing as WoF changes work well.
