### ISSUE TITLE
Populating Pelias in Production

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#12]
TriMet could use help setting up a production system, and having a cron job automated the data population of that system. Basically, learn what MapZen did to keep the system both up and up-to-date.

**Comment by fpurcell** [comment]
FYI, I have a copy /data dir process, which might be my go-to method for near future...

**Comment by orangejulius** [comment]
I'm glad the data copy worked :)

I can think of some cases it won't, such as when we change the Pelias Elasticsearch schema. we can work to find ways to handle that case easily too

**Comment by fpurcell** [comment]
copy seems to be my go forward plan...closing

**Comment by orangejulius** [comment]
👍 if there is anything that you think of that would help, let us know
