### ISSUE TITLE
just pelias.json (no more OpenTransitTools/pelias.dockerfiles)

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#14]
We have a project called https://github.com/OpenTransitTools/pelias.dockerfiles, which was created mainly to add the transit loader to be part of the docker-compose orchestration.

Eventual goal is to just use https://github.com/pelias/dockerfiles, and define in pelias.json "transit gtfs" or "intersections", and pelias/dockerfiles will know to use the transit loader, etc...

(p.s., this was discussed at the April 2018 MOD meeting)

**Comment by orangejulius** [comment]
It looks like @missinglink is basically solving this with the huge improvement over in https://github.com/pelias/dockerfiles/pull/61

**Comment by fpurcell** [comment]
Done
