### ISSUE TITLE
Discussion Aug 23, 2018

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#21]
1.  #22 -- negative sources to eliminate wof from being queried.

2. When will we get BOOSTING for search & autocomplete?

2b. If long time, can me merge BOOSTING into master now, since we might be missing something ala entrances, etc...

3. I see this in the logs for loading...don't like the static naming of osm.pbf, since my file was or-wa.pbf (I've changed the name, but).
Starting pelias_libpostal_baseimage: cannot access '/data/openstreetmap/*.osm.pbf': No such file or directory

4. Airport, entrance snapping, etc...  (Madeline)

5. Address Patching #8 ... Madeline & Myleen mentioned possibly patching OSM data in addition to OA, due to the PDX airport issue.  Frank thought maybe record removal could be an available option to users of the patch mechanism (e.g., with removal, we could simply get rid of the problematic PDX point coming from OSM, and rely on the TriMet landmark (which Myleen places specific to trip planning) that's loaded via the transit loader.

**Comment by orangejulius** [comment]
Let's chat more tomorrow but:

1.) I don't recommend attempting to make that query return no results. I would recommend a query like this: https://ws-st.trimet.org/pelias/v1/search?text=Sellwood&sources=transit,osm,geonames,oa

Something we have considered in the past, which might be useful for custom Pelias installations, is a _negative_ sources option. Something like `sources=-whosonfirst` which would include all sources but whosonfirst. That avoids the need to know about and list _all_ the other sources.

2.) I've just updated the `configurable-boosts` branch to include all the latest API changes. There is one change that _may_ help with any unexpected `whosonfirst` results. I'll look into merging the autocomplete changes ASAP, the search changes are coming along and may be able to be merged separately.

3.) I think what you're talking about is how the name of the pbf file needs to be known in advance. I agree it would be nice to make that more friendly.

**Comment by fpurcell** [comment]
Hey Julian, yeah sources=-whosonfirst would work well ... I created a ticket as such. #22 

BTW, I am capturing query issues on ticket #20.  The most interesting issue so far is the wrong city problem ... we have addresses in an unincorporated area called "Bull Mountain" (https://ws-st.trimet.org/pelias/v1/search?text=Bull%20Mountain and https://en.wikipedia.org/wiki/Bull_Mountain,_Oregon) ... if folks used either "Bull Mountain" or "TIgard" (and maybe even "Portland"), that could be a valid address. But right now, Pelias will return just the city record anytime the wrong city is used in the query. I'd rather see Pelias drop the city (and state) parts from the request and resubmit the search with just the address (sans city/state/etc...).

**Comment by orangejulius** [comment]
Regarding points 4 and 5, Peter and I had discussed something similar a while ago too.

I really like the idea of switching gears from "patch" functionality to essentially configurable record blacklists in each importer, coupled with a powerful way for you to add custom records. The "landmark" functionality is a start but we have wanted to add custom CSV and GeoJSON importers for a long time anyway. This would probably end up being easier to manage.

**Comment by fpurcell** [comment]
all these items discussed, active in other tickets .. closing
