### ISSUE TITLE
Intersection Format

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#25]
Would like to request an additional intersection format:
  1. one where the streets are separated by a comma, ala '9,Lambert'
  1. so https://ws-st.trimet.org/pelias/v1/search?text=9,Lambert would find the same results as https://ws-st.trimet.org/pelias/v1/search?text=9%20%26%20Lambert
  1. Myleen reports: Learned something new about how Rider Support looks up intersections.  For example, if they are looking for 'SW 6th & Pine', some of them will use '6,pine', which works in the SOLR instance (that is, will bring up intersections).
  1. Do they not use directions (NW,SE) / types (St,Ave)?  "Some don't, no"
  1. See also: https://github.com/pelias/model/pull/111
  1. See also: #24

**Comment by orangejulius** [comment]
We are looking at (finally) removing or lessening the significance of commas for the autocomplete endpoint (they already are ignored in the search endpoint I believe). That would take care of issue 1.

We also are now, after merging https://github.com/pelias/schema/pull/310, able to consider dropping the requirement that all directionals and street types match in a query. That should at least get us closer to supporting something like "6,pine"

**Comment by fpurcell** [comment]
Thanks Julian. Yeah, I want to discuss this a bit more next time we talk. I could (badly/inefficiently) handle the "9,Main" intersection format via the wrapper (I think). But seeing the various formats in https://github.com/pelias/model/pull/111, I'm kinda hoping that there's a built-in more streamlined solution. Anyway, talk soon...

**Comment by fpurcell** [comment]
Closing ... we're not worrying about 9,Main ... etc...
