### ISSUE TITLE
Mount Tabor Park

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#27]
We're trying to get Mount Tabor Park to show up in autocomplete & search results.

Spelling out the name works:
https://ws-st.trimet.org/pelias/v1/autocomplete?text=Mount%20Tabor%20Park
https://ws-st.trimet.org/pelias/v1/search?text=Mount%20Tabor%20Park

But abbrev. Mt Tabor Park does not:
https://ws-st.trimet.org/pelias/v1/autocomplete?text=Mt%20Tabor%20Park
https://ws-st.trimet.org/pelias/v1/search?text=Mt%20Tabor%20Park

Tried to add an alias, but no luck there either:
Mt Tabor Park,Mount Tabor Park,Mt Tabor Pk

**Comment by fpurcell** [comment]
p.s., my guess is that both Mount and Park are already aliased / synonymed out, and that's getting in the way...

**Comment by orangejulius** [comment]
Interesting. We do/did have special handling for [Mount](https://github.com/pelias/schema/issues/157), but I don't recall it's current status. We can look into it.

**Comment by missinglink** [comment]
I've opened up two PRs today against `addressit` to deal with the parsing issues.

**Comment by missinglink** [comment]
And one PR for `pelias/schema` to add synonyms

**Comment by missinglink** [comment]
The changes can be tested with the following diff to `docker-compose.yml`:

```diff
   schema:
-    image: pelias/schema:master
+    image: pelias/schema:name_synonyms-2019-03-04-3f488cb1546ac519ae84ff0a4c70504f75af8f22
     container_name: pelias_schema
     user: "${DOCKER_USER}"
     volumes:
       - "./pelias.json:/code/pelias.json"
   api:
-    image: pelias/api:master
+    image: pelias/api:do_not_parse_first_token_as_state_abbr-2019-03-04-9c605afd5c66aa36c78a95388755b62b481a76a7
     container_name: pelias_api
     user: "${DOCKER_USER}"
     restart: always
```

**Comment by orangejulius** [comment]
It looks like this is still actually an issue! We are doing a big push on abbreviations over in https://github.com/pelias/schema/pull/453, and I think that will fix this case once and for all :crossed_fingers: 

We can add a test case for Mt Tabor Park to be sure

**Comment by fpurcell** [comment]
This seems to work pretty well now.
