### ISSUE TITLE
3480 NW INDUSTRIAL ST failing ... November 2020

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#35]
https://ws.trimet.org/pelias/v1/search?text=3480%20NW%20Industrial%20St,%20Portland
"text": "3480 NW INDUSTRIAL ST Portland Oregon"

stopped working on Nov 3rd ???

**Comment by fpurcell** [comment]
This address came from our ticket office. It is the lot just west of 3460, and the address is on the gate. Was a towing company at one point, unsure if that is still the case, but address was still on gate as of the Nov 2019 StreetView.

**Comment by missinglink** [comment]
This query is working correctly on the Geocode Earth hosted service:
https://pelias.github.io/compare/#/v1/search?text=3480+NW+INDUSTRIAL+ST+Portland+Oregon

Although worth noting that it's an `interpolated` address, so would rely on the interpolation service working correctly and the street being available.

<img width="705" alt="Screenshot 2020-11-04 at 09 47 22" src="https://user-images.githubusercontent.com/738069/98039015-e7e41b80-1e82-11eb-9abd-1d3908b783a3.png">

<img width="406" alt="Screenshot 2020-11-04 at 09 47 43" src="https://user-images.githubusercontent.com/738069/98039025-ed416600-1e82-11eb-872c-75605814f591.png">

**Comment by missinglink** [comment]
When I click the link above it seems to work for me on your server too?
https://ws.trimet.org/peliaswrap/v1/search?text=3480%20NW%20Industrial%20St,%20Portland

<img width="736" alt="Screenshot 2020-11-04 at 09 51 35" src="https://user-images.githubusercontent.com/738069/98039276-55904780-1e83-11eb-9746-72d3f910bcd1.png">

**Comment by fpurcell** [comment]
Hey Peter,  Thanks for checking it out.  Yeah, the issue is on the load server ... not deployed to production yet.

```
// 20201103125841
// http://rj-dv-mapgeo01:4000/v1/search?text=3480%20NW%20Industrial%20St,%20Portland

{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://rj-dv-mapgeo01:4000/attribution",
    "query": {
      "text": "3480 NW Industrial St, Portland",
      "size": 10,
      "private": false,
      "focus.point.lat": 45.52,
      "focus.point.lon": -122.67,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "via": "header",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "housenumber": "3480",
        "street": "nw industrial st",
        "city": "portland"
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1604437121184
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.712764,
          45.541218
        ]
      },
      "properties": {
        "id": "polyline:27095",
        "gid": "openstreetmap:street:polyline:27095",
        "layer": "street",
        "source": "openstreetmap",
        "source_id": "polyline:27095",
        "name": "NW Industrial St",
        "street": "NW Industrial St",
        "confidence": 0.8,
        "match_type": "fallback",
        "distance": 4.087,
        "accuracy": "centroid",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Oregon",
        "region_gid": "whosonfirst:region:85688513",
        "region_a": "OR",
        "county": "Multnomah County",
        "county_gid": "whosonfirst:county:102081631",
        "county_a": "MU",
        "locality": "Portland",
        "locality_gid": "whosonfirst:locality:101715829",
        "neighbourhood": "Northwest Industrial",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85871505",
        "label": "NW Industrial St, Portland, OR, USA"
      },
      "bbox": [
        -122.719134,
        45.54109,
        -122.706456,
        45.541301
      ]
    }
  ],
  "bbox": [
    -122.719134,
    45.54109,
    -122.706456,
    45.541301
  ]
}
```

**Comment by missinglink** [comment]
My first intuition is that the environment where you're experiencing the issue doesn't have the interpolation service built/configured correctly.

**Comment by orangejulius** [comment]
Also, as Peter pointed out, it's an interpolated address, meaning it won't work with autocomplete.

**Comment by fpurcell** [comment]
FYI, http://rj-dv-mapgeo01:4000/v1/search?text=3440%20NW%20Industrial%20St,%20Portland  
(a nearby interpolated address)

**Comment by fpurcell** [comment]
```
// 20201103130727
// http://rj-dv-mapgeo01:4000/v1/search?text=3440%20NW%20Industrial%20St,%20Portland

{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://rj-dv-mapgeo01:4000/attribution",
    "query": {
      "text": "3440 NW Industrial St, Portland",
      "size": 10,
      "private": false,
      "focus.point.lat": 45.52,
      "focus.point.lon": -122.67,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "via": "header",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "housenumber": "3440",
        "street": "nw industrial st",
        "city": "portland"
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1604437646951
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.7174368,
          45.5412496
        ]
      },
      "properties": {
        "id": "polyline:27095",
        "gid": "mixed:address:polyline:27095",
        "layer": "address",
        "source": "mixed",
        "source_id": "polyline:27095",
        "name": "3440 NW Industrial St",
        "housenumber": "3440",
        "street": "NW Industrial St",
        "confidence": 0.8,
        "match_type": "interpolated",
        "distance": 4.087,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Oregon",
        "region_gid": "whosonfirst:region:85688513",
        "region_a": "OR",
        "county": "Multnomah County",
        "county_gid": "whosonfirst:county:102081631",
        "county_a": "MU",
        "locality": "Portland",
        "locality_gid": "whosonfirst:locality:101715829",
        "neighbourhood": "Northwest Industrial",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85871505",
        "label": "3440 NW Industrial St, Portland, OR, USA"
      }
    }
  ],
  "bbox": [
    -122.7174368,
    45.5412496,
    -122.7174368,
    45.5412496
  ]
}
```

**Comment by fpurcell** [comment]
btw, http://maps7.trimet.org/pelias/ has latest data and configs

FYI, the tests that have search?text=3480%20NW%20Industrial%20St,%20Portland passed on Oct 22nd.  And last night, with updated OSM data, the tests are failing.

**Comment by fpurcell** [comment]
BTW @missinglink & @orangejulius ... I just updated the OSM data, re-installed Docker containers, re-loaded the Pelias from scratch and still see the 3480 NW INDUSTRIAL interpolation just going to NW INDUSTRIAL.

**Comment by missinglink** [comment]
Someone reported to us via email this week that the US Census TIGER mirror we are using (https://census-backup.s3.amazonaws.com/) is no longer serving files.

It might be related to what you're seeing, since the interpolation ranges might be less precise without it 🤷 

Might be worth a quick scan of the interpolation logs (near the start) to see if it's failed to download that data.

**Comment by missinglink** [comment]
I've mirrored the TIGER census data to our servers: https://github.com/pelias/interpolation/pull/265

Could be a red herring and totally unrelated but if you fancy trying the dev tag (pelias/interpolation:tiger_mirror) it might fix it.

https://hub.docker.com/layers/pelias/interpolation/tiger_mirror/images/sha256-33894544d1d0dc2bde393f66ef64eb4a87413baa5377dac32d041578797bdb14?context=explore

**Comment by fpurcell** [comment]
Thanks Peter!  I'm reloading now.  BTW, in previous logs, I did see a tiger error, so fingers crossed this is the fix.

**Comment by missinglink** [comment]
I've merge it to `master`

**Comment by fpurcell** [comment]
Success.  TIGER fix fixed the INDUSTRIAL issue.  Thanks again, Peter!
