### ISSUE TITLE
commas in search causes problems (e.g., Starbucks, Lake Oswego)

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#5]
This issue: https://github.com/pelias/pelias/issues/673

It feels like POI searches in Pelias sometimes take a backseat to addresses searching, and the "Starbucks Lake Oswego" (w/out a comma) issue seems to highlight that. When I find other POI searching in Pelias to be not so intuitive (e.g., "I asked for Park & Ride X...why didn't that come up in my results?"), it feels like the same the "Starbucks Lake Oswego" (no comma) issue might be at play.

BTW, here's what the problem looks like on TriMet's Pelias instance:
https://ws-st.trimet.org/pelias/v1/search?text=Starbucks%20Lake%20Oswego
vs.
https://ws-st.trimet.org/pelias/v1/search?text=Starbucks,%20Lake%20Oswego

Note that the first URL w/out a comma you don't get any hits for Starbucks Coffee (at least for the first N results), whereas adding in a comma brings nothing but Startbucks Coffee POIs.

**Comment by missinglink** [comment]
I've opened https://github.com/pelias/api/pull/1251 as a potential solution to this issue.

**Comment by orangejulius** [comment]
As mentioned in the linked Pelias issue, this problem should be pretty definitively fixed by the new Pelias parser. For example, for the query above:
![image](https://user-images.githubusercontent.com/111716/66160472-3841d780-e5f8-11e9-9131-6649b8932f57.png)

**Comment by fpurcell** [comment]
done
