### ISSUE TITLE
boost elements based on 'source' or 'layers' values

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#7]
I want the ability to boost certain types of data, via either the 'source' or the 'layers' attributes.

I've got new 'source' values for transit elements. For example, I'd like to add a boost value to things like transit stops ('layers=stops') to have them appear higher in the Pelias results than other elements, which might otherwise appear higher in a search w/out any boost setting.

**Comment by fpurcell** [comment]
One example is https://ws-st.trimet.org/pelias/v1/autocomplete?text=211.  I'm hoping that by boosting our 'transit' **source** as more preferred than other sources, I'll see my Stop ID 211 atop my results, ala https://ws-st.trimet.org/pelias/v1/autocomplete?text=Stop%20ID%20211

**Comment by fpurcell** [comment]
BTW, I would like the ability to 'additively' boost certain classes of data in Pelais to make some things even that much more preferred.  For example, maybe I boost both a **source** = 'transit' and further boost **layer** = 'stops'.  Thus I'm intending that my "Stop ID 211" will appear higher in a search when the term = "211" compared to maybe a "Park & Ride 211" coming from the same transit source, but a different layer, etc...

**Comment by fpurcell** [comment]
IMPORTANT NOTE:  I also want to see stuff from my transit sources considered before other sources.  A search for "Sunset TC", for example https://ws-st.trimet.org/pelias/v1/autocomplete?text=Sunset%20TC or https://ws-st.trimet.org/pelias/v1/autocomplete?text=Sunset%20Transit%20Center  should always come from my transit data first (as opposed to it coming from OSM).  Although this might also be a strangeness between search and autocomplete, ala #19

**Comment by fpurcell** [comment]
Another thing...we have a lot of Fred Meyer's (grocery store chain) in Oregon.  When I boost, I want to see results from those boosted sources and layers.

So basically, the results from this query:  https://ws-st.trimet.org/pelias/v1/autocomplete?text=Fred%20Meyer
Should look a lot more like these results: https://ws-st.trimet.org/pelias/v1/autocomplete?text=Fred%20Meyer%20HOP 
(shouldn't have to add the HOP to the query to find items if they're in a source that's been boosted, results from the boosted layers will appear higher according to the individual boost level).

**Comment by orangejulius** [comment]
Another example case, I think this is similar to the others:
https://ws-st.trimet.org/pelias/v1/search?text=ID%2011

**Comment by missinglink** [comment]
This feature is ready for testing and we'd be happy for feedback.

**Comment by missinglink** [comment]
At time of writing it's still in a branch, we plan to merge to master soon.

https://github.com/pelias/api/pull/1173

**Comment by fpurcell** [comment]
this is done.  excellent work
