### ISSUE TITLE
Patch process ... for quick turnaround fixes and additions

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#8]
JUNE 2018: 
A need to patch addresses and points seems to be an emerging requirement.  This ticket talked a lot about patching (esp in regards to OA data), so renaming and will elaborate the needs below:

In order to perform more timely fixes to day (esp data like OA, which could have a long / undefined turnaround time), we're going to need a 'patch' process similar to something we have in place today for Portland Metro Master Address (MA) data. 

In the current MA process mentioned above, Madeline and Myleen have a .csv file that allows them to 'fix' addresses in the source MA data before it gets into SOLR. We need a similar OA patch process for Pelias, and the OA loader seems like the place to do this.

The .csv 'patch' file exists here: https://github.com/OpenTransitTools/loader/blob/master/ott/loader/geocoder/data/maf_fixes.csv   The coords are in Oregon State Plane North (we'd use lat/lon for OA). The process is to exactly match the values of 'address', 'city' and 'zip_code' in the MA data source with entries in this file, and then override MA coordinates (since those coords are misplaced in the source data).  If the 'issue' field (comment) begins with the word 'Add ' (or 'add '), then the entry is appended to MA table.  With the MA table loaded and patched, the corrected data then flows into SOLR.

**Comment by fpurcell** [comment]
About the 'patch' process mentioned above: maybe this interface https://mod.netlify.com/#/intro (developed for MOD) could provide a better way to patch the OA data.

But first, I have some questions about the mod.netlify.com interface:
 1. if I find an existing record in OA with bad X,Y coordinates (e.g., PLACE_BLAH = POINT(-122.0, 45.0)), can I fix that broken record via the MOD interface? If I add a file with a 'patch' for PLACE_BLAH = POINT(-122.476, 46.282) with fixed coordinates, what happens to the data in OA?  Will OA now have 1 or 2 records for PLACE_BLAH?  Will my new record override the older PLACE_BLAH? Or will OA now contain 2 records for PLACE_BLAH, the original record with the broken X,Y and my record with the newly fixed X,Y?
 2. collecting all the 'patch' records in a single file gives a good record of what has changed over time. Again, if I repeatedly applied the same patch file multiple times, am I repeatedly adding new records to OA? Or will repeated updates override existing records in OA?

Thoughts?

**Comment by missinglink** [comment]
note to self: the `maf_fixes.csv` coordinates are in [SRID 2913](https://epsg.io/2913-1901).

**Comment by missinglink** [comment]
@fpurcell regarding your questions above:

1. You can't modify OA, either using the [Submit Service](https://github.com/openaddresses/submit-service) or any other method.

This is by design, the OA data is authoritative data from governmental sources, it's not the same as Openstreetmap where they encourage community fixes.

I brought up the issue with the OA team in August and Ian Dees said:

> ... we've had on our plan for ages to have some sort of "clean up"/"post processing" workflow that the data goes through as it makes its way into the output data. we'd have some default set of operations that the cleanup does and that we distribute, but it would be extensible so others could run their own steps in addition to/instead of what we do. one of those steps would be an "override" file that could be applied with the goal of the override being that it could end up going back to the data provider as improvements they could apply if they wanted.

> which is to say we'd love to have that cleanup/override information, but don't have a way to apply it yet.

2. The patches would likely need to be [idempotent](https://en.wikipedia.org/wiki/Idempotence) so that they can be applied multiple times without changing the result beyond the initial application.

**Comment by fpurcell** [comment]
FYI ... closing this issue, since with banning + generic loader, I think that's the go-forward with patching
