### ISSUE TITLE
Add the 'sources' list (specifically 'transit') via pelias.json config file

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#9]
Need the ability to add new values to the Pelias API for the 'sources' list (specifically 'transit') via pelias.json config file.  

Currently, we get an error on custom source values: https://ws-st.trimet.org/pelias/v1/autocomplete?text=822%20Stop%20ID&sources=transit

**Comment by missinglink** [comment]
hi @fpurcell this issue has now be resolved by:

- https://github.com/pelias/api/pull/1131
- https://github.com/pelias/config/pull/83

Documentation is provided on https://github.com/pelias/api/pull/1131

**Comment by fpurcell** [comment]
Closing ... DONE
